bindkey -s '^[OP' 'play -n synth 0.1 sine C#4 > /dev/null 2>&1^J'
bindkey -s '^[OQ' 'play -n synth 0.1 sine D#4 > /dev/null 2>&1^J'
bindkey -s '^[OR' 'play -n synth 0.1 sine E#4 > /dev/null 2>&1^J'
bindkey -s '^[OS' 'play -n synth 0.1 sine F#4 > /dev/null 2>&1^J'
bindkey -s '^[[15~' 'play -n synth 0.1 sine G#4 > /dev/null 2>&1^J'
bindkey -s '^[[17~' 'play -n synth 0.1 sine A#4 > /dev/null 2>&1^J'
bindkey -s '^[[18~' 'play -n synth 0.1 sine B#4 > /dev/null 2>&1^J'
bindkey -s '^[[19~' 'source csminor.sh > /dev/null 2>&1^J'
