bindkey -s '^[OP' 'play -n synth 0.1 sine Eb4 > /dev/null 2>&1^J'
bindkey -s '^[OQ' 'play -n synth 0.1 sine F4 > /dev/null 2>&1^J'
bindkey -s '^[OR' 'play -n synth 0.1 sine Gb4 > /dev/null 2>&1^J'
bindkey -s '^[OS' 'play -n synth 0.1 sine Ab4 > /dev/null 2>&1^J'
bindkey -s '^[[15~' 'play -n synth 0.1 sine Bb4 > /dev/null 2>&1^J'
bindkey -s '^[[17~' 'play -n synth 0.1 sine Cb5 > /dev/null 2>&1^J'
bindkey -s '^[[18~' 'play -n synth 0.1 sine Db5 > /dev/null 2>&1^J'
bindkey -s '^[[19~' 'source ebmajor.sh > /dev/null 2>&1^J'
